routes/web.php
<?php

// use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
// use App\HTTP\Controllers\StudentController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CartController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('student', StudentController::class);
Route::prefix('admin')->group(function () {
    Route::resource('department', DepartmentController::class)->middleware('auth');
    Route::prefix('product')->group(function () {
        Route::get('/', [ProductController::class, 'index'])->name('indexProduct');
        Route::get('create', [ProductController::class, 'create']);
        Route::post('store', [ProductController::class, 'store'])->name('addProduct');
        Route::get('edit/{id}', [ProductController::class, 'edit'] )->name('editProduct');
        Route::post('update/{id}', [ProductController::class, 'update'] )->name('updateProduct');
        Route::post('delete', [ProductController::class, 'destroy'])->name('deleteProduct');
    });
});

Route::get('/login', [LoginController::class, 'index'] )->name('login');
Route::post('/login', [LoginController::class, 'login']);
Route::post('/register', [LoginController::class, 'register'])->name('register');
// Route::post('/xuly', [LoginController::class, 'login1']);
Route::get('/', function () {
        $dataProducts = DB::table('products')
            ->join('departments', 'products.department_id', '=', 'departments.id')
            ->select('products.id', 'products.name', 'products.image', 'departments.slug as department_slug', 'products.price', 'products.discount_flag', 'products.discounted_price', 'products.status', 'products.quantity', 'products.weight', 'products.volume', 'products.description', 'products.date_add', 'products.last_modifer')
            ->get()->toArray();
        $dataProducts = json_decode(json_encode($dataProducts), true);
            return view('index', [
                'dataDepartments' => \App\Models\Department::where('status', 1)->get(),
                'dataProducts' => $dataProducts,
            ]);
        }
    );
Route::get('cart',[CartController::class, 'addCart'])->middleware('auth');
Route::get('/go-to-cart', [CartController::class, 'cart'])->middleware('auth');
Route::get('/removeItemCart', [CartController::class, 'removeItemCart'] )->middleware('auth');
Route::get('check', [CartController::class, 'check'] );
Route::get('/logout', [LoginController::class, 'logout']);






Route::get('/test3', function () {
    return view('index1');
});
Route::get('/test', function(){
    return $host = request()->getHost();
});
Route::get('/test2', function() {
    return [1, 2, 3];
});
Route::get('/home', function () {
    return response()
            ->json(['name' => 'Abigail', 'state' => 'CA']);
});
//Route::get('/admin', [AdminController::class, 'index']);
Route::any('/product', function() {});
Route::get('user/{id}');
Route::get('/user', [UserController::class, 'index']);
// Route::resource([
//     'Cate' => CategoryController::class
// ]);

resources/views/cart.blade.php
@extends('layoutIndex')
@section('content')
    <section class="breadcrumb-section set-bg" data-setbg="img/breadcrumb.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Shopping Cart</h2>
                        <div class="breadcrumb__option">
                            <a href="./index.html">Home</a>
                            <span>Shopping Cart</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shoping Cart Section Begin -->
    <section class="shoping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__table">
                        <table>
                            <thead>
                            <tr>
                                <th class="shoping__product">Sản phẩm</th>
                                <th>Giá gốc</th>
                                <th>Giá thanh toán</th>
                                <th>Số lượng</th>
                                <th>Total</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @if ($listCart)
                                @foreach($listCart as $dataCart)
                                    <tr id="itemCart-{{ $dataCart->id }}">
                                        <td class="shoping__cart__item">
                                            <img src="{{ asset('storage/img/product/'.$dataCart->image) }}" alt="" style="max-height: 100px; max-width: 100px">
                                            <h5>{{ $dataCart->name }}</h5>
                                        </td>
                                        <td class="shoping__cart__price original_price" style="text-decoration: line-through; text-decoration-thickness: 0.2rem; text-decoration-color: red">
                                            {{ $dataCart->price }}
                                        </td>
                                        <td class="shoping__cart__price" id="price-{{ $dataCart->id }}">
                                            {{ $dataCart->discounted_price != "" ? $dataCart->discounted_price : $dataCart->price }}
                                        </td>
                                        <td class="shoping__cart__quantity">
                                            <div class="quantity">
                                                <div class="pro-qty">
                                                    <span class="dec qtybtn" onclick="calculate({{$dataCart->id}}, 'dec')">-</span>
                                                    <input type="text" class="soluong" id="quantity-{{ $dataCart->id }}" value="{{ session('cart.'.$dataCart->id) }}" readonly="true">
                                                    <span class="inc qtybtn" onclick="calculate({{$dataCart->id}}, 'inc')">+</span>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="shoping__cart__total gia_don_hang" id="priceSub-{{$dataCart->id}}">
                                            {{ $dataCart->discounted_price != "" ? $dataCart->discounted_price *  session('cart.'.$dataCart->id)  : $dataCart->price *  session('cart.'.$dataCart->id)  }}
                                        </td>
                                        <td class="shoping__cart__item__close">
                                            <span class="icon_close" onclick="removeItemCart({{$dataCart->id}})"></span>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                            @else
                                <tr><h1>Not Found</h1></tr>
                            @endif
                        </table>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__btns">
                        <a href="#" class="primary-btn cart-btn">CONTINUE SHOPPING</a>
                        <a href="#" class="primary-btn cart-btn cart-btn-right"><span class="icon_loading"></span>
                            Upadate Cart</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="shoping__continue">
                        <div class="shoping__discount">
                            <h5>Discount Codes</h5>
                            <form action="#">
                                <input type="text" placeholder="Enter your coupon code">
                                <button type="submit" class="site-btn">APPLY COUPON</button>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="shoping__checkout">
                        <h5>Cart Total</h5>
                        <ul>
                            <li>Tổng tiền <span id="total_price"></span></li>
                            <li>Số tiền phải thanh toán <span id="total_price_pay"></span></li>
                        </ul>
                        <a href="#" class="primary-btn">PROCEED TO CHECKOUT</a>
                    </div>
                </div>
                <script>
                    var original_price = document.getElementsByClassName('original_price')
                    var gia_don_hang = document.getElementsByClassName('gia_don_hang')
                    var soluong = document.getElementsByClassName('soluong')
                    var total_price = 0
                    var total_price_pay = 0
                    for (let i = 0; i < original_price.length; i++) {
                        console.log(original_price[i].innerHTML)
                        console.log(soluong[i].value)
                        total_price += parseInt(original_price[i].innerHTML)*parseInt(soluong[i].value)
                    }
                    for (const data1 of gia_don_hang) {
                        total_price_pay += parseInt(data1.innerHTML)
                    }
                    document.getElementById('total_price').innerHTML = total_price
                    document.getElementById('total_price_pay').innerHTML = total_price_pay
                </script>
            </div>
        </div>
    </section>
@endsection

resources/views/create.blade.php
@extends('layout')
@section('content')
    <div class="container">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <h3>Add Student</h3>
                </div>
                <div class="col-md-6">
                    <a href="{{route('student.index')}}" class="btn btn-primary float-end">Back manager student</a>
                </div>
                <div class="card-body">
                    <form action="{{route('student.store')}}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Email address</label>
                                <input type="text" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Password</label>
                                <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Name</label>
                                <input type="text" class="form-control" name="name" id="exampleInputPassword1">
                            </div>
                            <div class="form-group">
                                <label class="exampleInputPassword1">Address</label>
                                <input type="text" class="form-control" name="address" id="exampleInputEmail1" aria-describedby="emailHelp" >
                            
                            </div>
                            <div class="form-group">
                                <label class="exampleInputPassword1">Phone</label>
                                <input type="text" class="form-control" name="phone" id="exampleInputEmail1" aria-describedby="emailHelp">
                            </div>
                            <input type="submit" class="btn btn-primary" value="Submit">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>    
@endsection

resources/views/index.blade.php
@extends('layoutIndex')
@section('content')
    <section class="hero">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="hero__categories">
                        <div class="hero__categories__all">
                            <i class="fa fa-bars"></i>
                            <span>Danh mục sản phẩm</span>
                        </div>
                        <ul>
                            @foreach($dataDepartments as $dataDepartment)
                                <li><a href="#">{{ $dataDepartment['department_name'] }}</a></li>
                            @endforeach
                        </ul>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="hero__search">
                        <div class="hero__search__form">
                            <form action="#">
                                <div class="hero__search__categories">
                                    All Categories
                                    <span class="arrow_carrot-down"></span>
                                </div>
                                <input type="text" placeholder="What do yo u need?">
                                <button type="submit" class="site-btn">SEARCH</button>
                            </form>
                        </div>
                        <div class="hero__search__phone">
                            <div class="hero__search__phone__icon">
                                <i class="fa fa-phone"></i>
                            </div>
                            <div class="hero__search__phone__text">
                                <h5>+65 11.188.888</h5>
                                <span>support 24/7 time</span>
                            </div>
                        </div>
                    </div>
                    <div class="hero__item set-bg" data-setbg="img/hero/banner.jpg">
                        <div class="hero__text">
                            <span>FRUIT FRESH</span>
                            <h2>Vegetable <br />100% Organic</h2>
                            <p>Free Pickup and Delivery Available</p>
                            <a href="#" class="primary-btn">SHOP NOW</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

    <!-- Categories Section Begin <section class="categories">--}}
{{--    <div class="container">--}}
    {{--        <div class="row">--}}
    {{--            <div class="categories__slider owl-carousel">--}}
    {{--                <div class="col-lg-3">--}}
    {{--                    <div class="categories__item set-bg" data-setbg="img/categories/cat-1.jpg">--}}
    {{--                        <h5><a href="#">Fresh Fruit</a></h5>--}}
    {{--                    </div>--}}
    {{--                </div>--}}
    {{--                <div class="col-lg-3">--}}
    {{--                    <div class="categories__item set-bg" data-setbg="img/categories/cat-2.jpg">--}}
    {{--                        <h5><a href="#">Dried Fruit</a></h5>--}}
    {{--                    </div>--}}
    {{--                </div>--}}
    {{--                <div class="col-lg-3">--}}
    {{--                    <div class="categories__item set-bg" data-setbg="img/categories/cat-3.jpg">--}}
    {{--                        <h5><a href="#">Vegetables</a></h5>--}}
    {{--                    </div>--}}
    {{--                </div>--}}
    {{--                <div class="col-lg-3">--}}
    {{--                    <div class="categories__item set-bg" data-setbg="img/categories/cat-4.jpg">--}}
    {{--                        <h5><a href="#">drink fruits</a></h5>--}}
    {{--                    </div>--}}
    {{--                </div>--}}
    {{--                <div class="col-lg-3">--}}
    {{--                    <div class="categories__item set-bg" data-setbg="img/categories/cat-5.jpg">--}}
    {{--                        <h5><a href="#">drink fruits</a></h5>--}}
    {{--                    </div>--}}
    {{--                </div>--}}
    {{--            </div>--}}
    {{--        </div>--}}
    {{--    </div>--}}
    {{--</section>
    {{----}}
        Categories Section End -->
    <!-- Featured Section Begin -->
    <section class="featured spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2>Featured Product</h2>
                    </div>
                    <div class="featured__controls">
                        <ul>
                            <li class="active" data-filter="*">All</li>
                            @foreach($dataDepartments as $dataDepartment)
                                <li data-filter=".{{ $dataDepartment['slug'] }}">{{ $dataDepartment['department_name'] }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row featured__filter">
                @foreach($dataProducts as $dataProduct)
                    <div class="col-lg-3 col-md-4 col-sm-6 mix {{ $dataProduct['department_slug'] }}">
                        <div class="featured__item">
                            <div class="featured__item__pic set-bg" data-setbg="{{ asset('storage/img/product/'.$dataProduct['image']) }}">
                                <ul class="featured__item__pic__hover">
                                    <li><a href="#"><i class="fa fa-heart"></i></a></li>
                                    <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                                    <li>
                                        @if (auth()->user())
                                            <a href="javascript:void(0)" onclick="addCart(this.id)" id="{{ $dataProduct['id'] }}"><i class="fa fa-shopping-cart"></i></a>
                                        @else
                                            <a href="javascript:void(0)" onclick="window.location.href='login'"><i class="fa fa-shopping-cart"></i></a>
                                        @endif
                                    </li>
                                </ul>
                            </div>
                            <div class="featured__item__text">
                                <h6><a href="#">{{ $dataProduct['name'] }}</a></h6>
                                <h5>{{ $dataProduct['price'] }}</h5>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </section>
@endsection

resources/views/index1.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
    @extends('layout')

    @section('content')
        <h1 style="text-align:center">Manager Student</h1>
            <div class="col-md-6">
                <a href="{{route('student.create')}}" class="btn btn-primary float-end">Add Student</a>
            </div>
            @if (Session::has('thongbao'))
            <div class="alert alert-success">
                {{Session::get('thongbao')}}
            </div>
            @endif
        <table class="table" align="center" style="width:60vw">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Password</th>
                <th scope="col">Address</th>
                <th scope="col">Phone</th>
                <th scope="col">Time Create</th>
                <th>
                    Action
                </th>
                </tr>
            </thead>
            <tbody>
                @php
                    $i = 1;
                @endphp
                @foreach ($student as $value)
                    <tr>
                        <th scope="row">{{$i++}}</th>
                        <td>{{$value['name']}}</td>
                        <td>{{$value['email']}}</td>
                        <td>{{$value['password']}}</td>
                        <td>{{$value['address']}}</td>
                        <td>{{$value['phone']}}</td>
                        <td>{{$value['create_at']}}</td>
                        <td>
                            <a href="#" style="text-decoration: none; padding: 5px 15px; background-color: #007BFF; color: white; border-radius: 3px">Edit</a>
                            <a href="#" style="text-decoration: none; padding: 5px 6px; background-color: #DC3545; color: white; border-radius: 3px">Delete</a>
                        </td>
                    </tr> 
                @endforeach
                
            </tbody>
        </table>
    @endsection

    {{-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script> --}}
</body>
</html>

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
    <link href="{{ asset('css/toastr.css') }}" rel="stylesheet">
    <link href="{{ asset('css/styleOfMe.css') }}" rel="stylesheet">
    <script src="{{ asset('js/toastr.js') }}"></script>
    <style type="text/css">
        @import url(https://fonts.googleapis.com/css?family=Roboto:300);
        .login-page {
          width: 360px;
          padding: 8% 0 0;
          margin: auto;
        }
        .form {
          position: relative;
          z-index: 1;
          background: #FFFFFF;
          max-width: 360px;
          margin: 0 auto 100px;
          padding: 45px;
          text-align: center;
          box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
        }
        .form input {
          font-family: "Roboto", sans-serif;
          outline: 0;
          background: #f2f2f2;
          width: 100%;
          border: 0;
          margin: 0 0 15px;
          padding: 15px;
          box-sizing: border-box;
          font-size: 14px;
        }
        .form button {
          font-family: "Roboto", sans-serif;
          text-transform: uppercase;
          outline: 0;
          background: #4CAF50;
          width: 100%;
          border: 0;
          padding: 15px;
          color: #FFFFFF;
          font-size: 14px;
          -webkit-transition: all 0.3 ease;
          transition: all 0.3 ease;
          cursor: pointer;
        }
        .form button:hover,.form button:active,.form button:focus {
          background: #43A047;
        }
        .form .message {
          margin: 15px 0 0;
          color: #b3b3b3;
          font-size: 12px;
        }
        .form .message a {
          color: #4CAF50;
          text-decoration: none;
        }
        /*.form .register-form {*/
        /* display: none;*/
        /*}*/
        .container {
          position: relative;
          z-index: 1;
          max-width: 300px;
          margin: 0 auto;
        }
        .container:before, .container:after {
          content: "";
          display: block;
          clear: both;
        }
        .container .info {
          margin: 50px auto;
          text-align: center;
        }
        .container .info h1 {
          margin: 0 0 15px;
          padding: 0;
          font-size: 36px;
          font-weight: 300;
          color: #1a1a1a;
        }
        .container .info span {
          color: #4d4d4d;
          font-size: 12px;
        }
        .container .info span a {
          color: #000000;
          text-decoration: none;
        }
        .container .info span .fa {
          color: #EF3B3A;
        }
        body {
          background: #76b852; /* fallback for old browsers */
          background: rgb(141,194,111);
          background: linear-gradient(90deg, rgba(141,194,111,1) 0%, rgba(118,184,82,1) 50%);
          font-family: "Roboto", sans-serif;
          -webkit-font-smoothing: antialiased;
          -moz-osx-font-smoothing: grayscale;
        }
    </style>
</head>
<body>
    @if ($errors->all())
        <?php
        foreach ($errors->all() as $message) {
            session()->flash('error_message', $message);
        }
        ?>
    @endif
    @if (Session::has('flash_message'))
        <script>
            toastr.option = {
                "progressBar" : true,
                "closeButton" : true,
            }
            toastr.success("{{ Session::get('flash_message') }}", 'Thành công!', {timeOut:8000});
            // toastr.info
        </script>
    @endif
    @if (Session::has('error_message'))
        <script>
            toastr.option = {
                "progressBar" : true,
                "closeButton" : true,
            }
            toastr.error("{{ Session::get('error_message') }}", 'Thất bại!', {timeOut:8000});
        </script>
    @endif


    <div class="login-page">
        <div class="form">
            <form class="login-form" action="{{ url('login') }}" method="POST" id="login-form">
                @csrf
                <input type="text" placeholder="username" name="email"/>
                <input type="password" placeholder="password" name="password"/>
                <button type="submit">login</button>
                <p class="message">Not registered? <a href="#" onclick="ToggleForm('login')">Create an account</a></p>
            </form>
            <form class="register-form" action="{{ route('register') }}" method="POST" id="register-form" style="display: none">
                @csrf
                <input type="text" placeholder="Nhập email" name="inputUser" value="{{ old('inputUser') }}"/>
                <input type="text" placeholder="Nhập họ" name="inputFirstName" value="{{ old('inputFirstName') }}"/>
                <input type="text" placeholder="Nhập tên" name="inputLastName" value="{{ old('inputLastName') }}"/>
                <input type="password" placeholder="Nhập mật khẩu" name="inputPassword"/>
                <input type="password" placeholder="Nhập lại mật khẩu" name="inputPassword_confirmation"/>
                <button type="submit">Register</button>
                <p class="message">Do you already have an account ? <a href="#" onclick="ToggleForm('register')">Login</a></p>
            </form>
            @if (session()->get('form') == 'register')
                <script>
                    document.getElementById('login-form').style.display = 'none'
                    document.getElementById('register-form').style.removeProperty('display')
                </script>

            @endif

        </div>
      </div>
    <script>
        function ToggleForm(action) {
            if (action == 'login') {
                document.getElementById('login-form').style.display = 'none'
                document.getElementById('register-form').style.removeProperty('display')
            } else {
                document.getElementById('register-form').style.display = 'none'
                document.getElementById('login-form').style.removeProperty('display')
            }
        }
    </script>
</body>
</html>