routes/web.php
<?php

// use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
// use App\HTTP\Controllers\StudentController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CartController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('student', StudentController::class);
Route::prefix('admin')->group(function () {
    Route::resource('department', DepartmentController::class)->middleware('auth');
    Route::prefix('product')->group(function () {
        Route::get('/', [ProductController::class, 'index'])->name('indexProduct');
        Route::get('create', [ProductController::class, 'create']);
        Route::post('store', [ProductController::class, 'store'])->name('addProduct');
        Route::get('edit/{id}', [ProductController::class, 'edit'] )->name('editProduct');
        Route::post('update/{id}', [ProductController::class, 'update'] )->name('updateProduct');
        Route::post('delete', [ProductController::class, 'destroy'])->name('deleteProduct');
    });
});

Route::get('/login', [LoginController::class, 'index'] )->name('login');
Route::post('/login', [LoginController::class, 'login']);
Route::post('/register', [LoginController::class, 'register'])->name('register');
// Route::post('/xuly', [LoginController::class, 'login1']);
Route::get('/', function () {
        $dataProducts = DB::table('products')
            ->join('departments', 'products.department_id', '=', 'departments.id')
            ->select('products.id', 'products.name', 'products.image', 'departments.slug as department_slug', 'products.price', 'products.discount_flag', 'products.discounted_price', 'products.status', 'products.quantity', 'products.weight', 'products.volume', 'products.description', 'products.date_add', 'products.last_modifer')
            ->get()->toArray();
        $dataProducts = json_decode(json_encode($dataProducts), true);
            return view('index', [
                'dataDepartments' => \App\Models\Department::where('status', 1)->get(),
                'dataProducts' => $dataProducts,
            ]);
        }
    );
Route::get('cart',[CartController::class, 'addCart'])->middleware('auth');
Route::get('/go-to-cart', [CartController::class, 'cart'])->middleware('auth');
Route::get('/removeItemCart', [CartController::class, 'removeItemCart'] )->middleware('auth');
Route::get('check', [CartController::class, 'check'] );
Route::get('/logout', [LoginController::class, 'logout']);






Route::get('/test3', function () {
    return view('index1');
});
Route::get('/test', function(){
    return $host = request()->getHost();
});
Route::get('/test2', function() {
    return [1, 2, 3];
});
Route::get('/home', function () {
    return response()
            ->json(['name' => 'Abigail', 'state' => 'CA']);
});
//Route::get('/admin', [AdminController::class, 'index']);
Route::any('/product', function() {});
Route::get('user/{id}');
Route::get('/user', [UserController::class, 'index']);
// Route::resource([
//     'Cate' => CategoryController::class
// ]);

resources/views/admin/departmentAdd.blade.php
@extends('admin.layoutAdmin')
@section('content')
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Thêm danh mục sản phẩm</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                <li class="breadcrumb-item active">Tables</li>
            </ol>
            <div class="card-body col-md-6 mx-auto" style="padding: 0">
                <form action="{{ route('department.store') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="departmentName">Tên danh mục</label>
                        <input style="width: 75%; display: inline;" type="text" class="form-control" name="departmentName" value="{{ old('departmentName') }}" id="departmentName" aria-describedby="emailHelp" placeholder="Nhập tên danh mục">

                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Trạng thái</label>
                        <select name="status" style="margin-left: 30px">
                            <option value="0" <?php old('status') == 1 ? 'selected' : '' ?>>Ẩn</option>
                            <option value="1" {{ old('status') == 1 ? 'selected' : ''}}>Hiện</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </main>
    <footer class="py-4 bg-light mt-auto">
        <div class="container-fluid px-4">
            <div class="d-flex align-items-center justify-content-between small">
                <div class="text-muted">Copyright &copy; Your Website 2023</div>
                <div>
                    <a href="#">Privacy Policy</a>
                    &middot;
                    <a href="#">Terms &amp; Conditions</a>
                </div>
            </div>
        </div>
    </footer>
@endsection

resources/views/admin/departmentEdit.blade.php
@extends('admin.layoutAdmin')
@section('content')
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Sửa danh mục sản phẩm</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                <li class="breadcrumb-item active">Tables</li>
            </ol>
            <div class="card-body col-md-6 mx-auto" style="padding: 0">
                <form action="{{ route('department.update', $dataDepartment['id']) }}" method="POST">
                    @csrf
                    @method('PATCH')
                    <div class="form-group">
                        <label for="departmentName">Tên danh mục</label>
                        <input style="width: 75%; display: inline;" type="text" class="form-control" name="departmentName" value="{{ $dataDepartment['department_name']  }}" id="departmentName" aria-describedby="emailHelp" placeholder="Nhập tên danh mục">

                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Trạng thái</label>
                        <select name="status" style="margin-left: 30px">
                            <option value="0" <?php $dataDepartment['status'] == 1 ? 'selected' : '' ?>>Ẩn</option>
                            <option value="1" {{ $dataDepartment['status'] == 1 ? 'selected' : ''}}>Hiện</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </main>
    <footer class="py-4 bg-light mt-auto">
        <div class="container-fluid px-4">
            <div class="d-flex align-items-center justify-content-between small">
                <div class="text-muted">Copyright &copy; Your Website 2023</div>
                <div>
                    <a href="#">Privacy Policy</a>
                    &middot;
                    <a href="#">Terms &amp; Conditions</a>
                </div>
            </div>
        </div>
    </footer>
@endsection

resources/views/admin/departments.blade.php
@extends("admin.layoutAdmin")
@section("content")
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Tables</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                <li class="breadcrumb-item active">Tables</li>
            </ol>
            <div class="card-body" style="padding: 0">
                <button type="button" onclick="window.location.href='/admin/department/create'" class="btn btn-primary float-right" style="margin-bottom: 10px">Thêm danh mục</button>
                <table class="table" style="border: 1px solid #E9ECEF" >
                    <thead class="thead-light">
                        <tr>
                            <th scope="row" style="text-align: center">STT</th>
                            <th scope="col" style="text-align: center">Danh mục sản phẩm </th>
                            <th scope="col" style="text-align: center">Ngày thêm</th>
                            <th scope="col" style="text-align: center">Ngày sửa gần đây</th>
                            <th scope="col" style="text-align: center">Trạng thái</th>
                            <th scope="col" style="text-align: center">Xử lý</th>
                        </tr>
                    </thead>
                    <?php $i =1; ?>
                    @foreach($dataDepartment as $value)
                    <tbody>
                        <tr>
                            <td style="text-align: center">{{ $i++ }}</td>
                            <td style="text-align: center">{{ $value['department_name'] }}</td>
                            <td style="text-align: center">{{ date("h:m d-m-Y",$value['date_add']) }}</td>
                            <td style="text-align: center">{{  $value['last_modifer'] != '' ? date("h:m d-m-Y", $value['last_modifer']) : '' }}</td>
                            <td style="text-align: center">{{ $value['status'] == 1 ?  'Hiển thị' : 'Ẩn' }}</td>
                            <td style="text-align: center">
                                <a class="btn btn-primary" href="{{ route('department.edit', $value['id']) }}" role="button">Edit</a>
                                <form action="{{ route('department.destroy', $value['id']) }}" method="POST" style="display: inline">
                                @csrf
                                @method('DELETE')
                                    <button class="btn btn-danger" >Delete</button>
                                </form>
{{--                                <a class="btn btn-danger" href="{{ route('department.destroy', $value['id']) }}" role="button">Delete</a>--}}
                            </td>
                        </tr>
                    </tbody>
                    @endforeach
                </table>
            </div>
        </div>
    </main>
    <footer class="py-4 bg-light mt-auto">
        <div class="container-fluid px-4">
            <div class="d-flex align-items-center justify-content-between small">
                <div class="text-muted">Copyright &copy; Your Website 2023</div>
                <div>
                    <a href="#">Privacy Policy</a>
                    &middot;
                    <a href="#">Terms &amp; Conditions</a>
                </div>
            </div>
        </div>
    </footer>
@endsection

resources/views/admin/layoutAdmin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Tables - SB Admin</title>
    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{{ asset('css/toastr.css') }}" rel="stylesheet">
    <link href="{{ asset('css/styleOfMe.css') }}" rel="stylesheet">
    <script src="{{ asset('js/toastr.js') }}"></script>
</head>
<body class="sb-nav-fixed">
    @if (Session::has('flash_message'))
        <script>
            toastr.option = {
                "progressBar" : true,
                "closeButton" : true,
            }
            toastr.success("{{ Session::get('flash_message') }}", 'Thành công!', {timeOut:8000});
            // toastr.info
        </script>
    @endif
    @if (Session::has('error_message'))
        <script>
            toastr.option = {
                "progressBar" : true,
                "closeButton" : true,
            }
            toastr.error("{{ Session::get('error_message') }}", 'Thất bại!', {timeOut:8000});
        </script>
    @endif

    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Start Bootstrap</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="index.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Interface</div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Layouts
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="layout-static.html">Static Navigation</a>
                                <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Pages
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="login.html">Login</a>
                                        <a class="nav-link" href="register.html">Register</a>
                                        <a class="nav-link" href="password.html">Forgot Password</a>
                                    </nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Error
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="401.html">401 Page</a>
                                        <a class="nav-link" href="404.html">404 Page</a>
                                        <a class="nav-link" href="500.html">500 Page</a>
                                    </nav>
                                </div>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Addons</div>
                        <a class="nav-link" href="{{ url('admin/department') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Danh mục sản phẩm
                        </a>
                        <a class="nav-link" href="{{ route('indexProduct') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Sản phẩm
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            @yield('content')

        </div>
    </div>
</body>
</html>

resources/views/admin/productAdd.blade.php
@extends('admin.layoutAdmin')
@section('content')
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Thêm sản phẩm</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                <li class="breadcrumb-item active">Tables</li>
            </ol>
            @if ($errors->any())
                <?php
                    foreach ($errors->all() as $error)
                    session()->flash('error_message', $error);
                ?>

            @endif
            <div class="card-body col-md-6 mx-auto" style="padding: 0">
                <form action="{{ route('addProduct') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row">
                        <label for="productName" class="col-sm-2 col-form-label">Tên danh mục</label>
                        <div class="col-sm-10">
                            <input style="width: 75%; display: inline;" type="text" class="form-control" name="productName" value="{{ old('productName') }}" id="productName" aria-describedby="emailHelp" placeholder="Nhập tên danh mục">
                        </div>

                    </div>
                    <div class="form-group row">
                        <label for="department" class="col-sm-2 col-form-label">Danh mục</label>
                        <div class="col-sm-10">
                            <select name="departmentID"  class="custom-select col-sm-6" >
                                @foreach($dataDepartments as $valueDepartment)
                                    <option value="{{$valueDepartment['id']}}" >{{ $valueDepartment['department_name'] }}</option>
                            @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="price" class="col-sm-2 col-form-label">Giá gốc</label>
                        <div class="col-sm-10">
                            <input style="width: 75%; display: inline;" type="text" class="form-control" name="price" value="{{ old('price') }}" id="price"  placeholder="Nhập giá">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="discounted_price" class="col-sm-2 col-form-label">Giá KM</label>
                        <div class="col-sm-10">
                            <input style="width: 75%; display: inline;" type="text" class="form-control" name="discounted_price" value="{{ old('discounted_price') }}" id="discounted_price"  placeholder="Nhập giá KM">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="quantity" class="col-sm-2 col-form-label">Số lượng</label>
                        <div class="col-sm-10">
                            <input style="width: 75%; display: inline;" type="text" class="form-control" name="quantity" value="{{ old('quantity') }}" id="quantity"  placeholder="Nhập số lượng">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="weight" class="col-sm-2 col-form-label">Cân nặng</label>
                        <div class="col-sm-10">
                            <input style="width: 75%; display: inline;" type="text" class="form-control" name="weight" value="{{ old('weight') }}" id="weight"  placeholder="Nhập cân nặng">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="volume" class="col-sm-2 col-form-label">Thể tích</label>
                        <div class="col-sm-10">
                            <input style="width: 75%; display: inline;" type="text" class="form-control" name="volume" value="{{ old('volume') }}" id="volume"  placeholder="Nhập kích thước">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="description" class="col-sm-2 col-form-label">Mô tả</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" id="description" name="description" rows="5"></textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="volume" class="col-sm-2 col-form-label">Trạng thái</label>
                        <div class="col-sm-10">
                            <select name="status"  class="custom-select col-sm-6" >
                                <option value="0">Ẩn</option>
                                <option value="1">Hiện</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="image" class="col-sm-2 col-form-label">Hình ảnh</label>
                        <div class="col-sm-10">
                            <input style="width: 75%; display: inline;" type="file" class="form-control" name="image" value="{{ old('image') }}" id="image" >
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary" style="display: block;margin: 0 auto;">Submit</button>
                </form>
            </div>
        </div>
    </main>
    <footer class="py-4 bg-light mt-auto">
        <div class="container-fluid px-4">
            <div class="d-flex align-items-center justify-content-between small">
                <div class="text-muted">Copyright &copy; Your Website 2023</div>
                <div>
                    <a href="#">Privacy Policy</a>
                    &middot;
                    <a href="#">Terms &amp; Conditions</a>
                </div>
            </div>
        </div>
    </footer>
@endsection

resources/views/admin/products.blade.php
@extends("admin.layoutAdmin")
@section("content")
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Sản phẩm</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                <li class="breadcrumb-item active">Sản phẩm</li>
            </ol>
            <div class="card-body" style="padding: 0">
                <button type="button" onclick="window.location.href='/admin/product/create'" class="btn btn-primary float-right" style="margin-bottom: 10px">Thêm Sản phẩm</button>
                <table class="table" style="border: 1px solid #E9ECEF" >
                    <thead class="thead-light">
                    <tr>
                        <th scope="col" style="text-align: center">STT</th>
                        <th scope="col" style="text-align: center">Tên Sản phẩm </th>
                        <th scope="col" style="text-align: center">Hình ảnh</th>
                        <th scope="col" style="text-align: center">Danh mục</th>
                        <th scope="col" style="text-align: center">Giá tiền</th>
                        <th scope="col" style="text-align: center">Thông tin</th>
                        <th scope="col" style="text-align: center">Status</th>
                        <th scope="col" style="text-align: center">Thời gian</th>
                        <th scope="col" style="text-align: center">Xử lý</th>
                    </tr>
                    </thead>
                    <?php $i =1; ?>
                    @foreach($dataProduct as $value)
                        <tbody>
                        <tr>
                            <td style="text-align: center">{{ $i++ }}</td>
                            <td style="text-align: center">{{ $value['name'] }}</td>
                            <td style="text-align: center"><img src="{{ asset('storage/img/product/'. $value['image']) }}" alt="..." class="img-thumbnail thumbnailProduct"></td>
                            <td style="text-align: center">{{ $value['department_name']}}</td>
                            <td style="text-align: center">
                                <small class="text-muted"><b>Giá gốc: {{ $value['price'] }}</b></small><br>
                                <small class="text-muted"><b>Giá KM: {{ $value['discounted_price'] ?? 'NULL'}}</b></small>
                            </td>
                            <td style="text-align: center">
                                <small class="text-muted"><b>Khối lượng: {{ $value['weight'] ?? 'NULL'}}</b></small><br>
                                <small class="text-muted"><b>Thể tích: {{ $value['volume'] ?? 'NULL'}}</b></small><br>
                                <small class="text-muted"><b>Số lượng: {{ $value['quantity'] ?? 'NULL'}}</b></small>
                            </td>
                            <td style="text-align: center">{!! $value['status'] == 1 ?  '<span class="badge badge-success">Hiển thị<span>' : '<span class="badge badge-danger">Ẩn </span>' !!}</td>
                            <td style="text-align: center">
                                <small class="text-muted"><b>Ngày nhập: {{ date("h:m d-m-Y", $value['date_add']) }}</b></small><br>
                                <small class="text-muted"><b>Lần sửa cuối: {{ $value['last_modifer'] != '' ? date("h:m d-m-Y", $value['last_modifer']) : "NULL"}}</b></small>
                            </td>
                            <td style="text-align: center">
                                <a class="btn btn-primary" href="{{ route('editProduct', $value['id']) }}">Edit</a>
                                <form action="{{ route('deleteProduct') }}" method="POST" style="display: inline">
                                    @csrf
                                    <input type="hidden" name="productID" value="{{ $value['id'] }}">
                                    <button class="btn btn-danger" onclick="return confirm('Bạn có muốn xóa sản phẩm này')">Delete</button>
                                </form>

                            </td>
                        </tr>
                        </tbody>
                    @endforeach
                </table>
            </div>
        </div>
    </main>
    <footer class="py-4 bg-light mt-auto">
        <div class="container-fluid px-4">
            <div class="d-flex align-items-center justify-content-between small">
                <div class="text-muted">Copyright &copy; Your Website 2023</div>
                <div>
                    <a href="#">Privacy Policy</a>
                    &middot;
                    <a href="#">Terms &amp; Conditions</a>
                </div>
            </div>
        </div>
    </footer>
@endsection